Taller.App/Taller.App.Front/Pages/Propietarios/EditarPropietario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Dominio;
using Taller.App.Persistencia;

namespace Taller.App.Front.Pages
{
    public class EditarPropietarioModel : PageModel
    {
        private static RepositorioPropietario repositoriop=new RepositorioPropietario(new Persistencia.ContextDb());
        public IEnumerable<Propietario> listaPropietar;
        public Propietario propietarioActual;

        public void OnGet(string id)
        {
            if (id != null)
            {
                this.propietarioActual=repositoriop.BuscarPropietario(id);
            }
        }

        public IActionResult OnPostEdit(Propietario propietario)
        {
            repositoriop.EditarPropietario(propietario);
            //this.ObtenerRepuestos();
            return RedirectToPage("/Propietarios/GestionPropietario", new {id = propietario.PropietarioId});

        }

        public void ObtenerPropietarios()
        {
             this.listaPropietar=(IEnumerable<Propietario>)repositoriop.ObtenerPropietarios();
             /*this.listaPropietar.Clear();
             foreach (var m in repositoriop.ObtenerPropietarios())
             {
                this.listaPropietar.Add(new Propietario(){
                PropietarioId=m.PropietarioId,
                nombre=m.nombre,
                telefono=m.telefono,
                fechaNacimiento=m.fechaNacimiento,
                contrasenia=m.contrasenia,
                ciudad=m.ciudad,
                correo=m.correo,
                });

             }*/
        }

    }
}

Taller.App/Taller.App.Front/Pages/Propietarios/GestionPropietario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Taller.App.Dominio;
using Taller.App.Persistencia;


namespace Taller.App.Front.Pages
{
    public class GestionPropietarioModel : PageModel
    {
        //cargar una lista sin la base de datos, 
        //public List<Propietar> listaPropietar=new List<Propietar>(){
            //new Propietar(){nombre="fredy", apellidos="llantero", telefono="neiva", nacimiento="01/10/1991", correo="kkmadrid@hotmail.com"},
            //new Propietar(){nombre="fredy", apellidos="llantero", telefono="neiva", nacimiento="01/10/1991", correo="kkmadrid@hotmail.com"},
            //new Propietar(){nombre="fredy", apellidos="llantero", telefono="neiva", nacimiento="01/10/1991", correo="kkmadrid@hotmail.com"}
            
        //};

        private static RepositorioPropietario repositoriop=new RepositorioPropietario(new Persistencia.ContextDb());

        public IEnumerable<Propietario> listaPropietar;

        public Propietario propietarioActual;

        public string textBuscar;

        public void OnGet(string id)
        {
            
            if (id !=null)
             {
                this.ObtenerPropietarios(id);;

             }else
             {
                this.ObtenerPropietarios();
             } 

            
        }

        public void OnPostDel(string id)
        {
            if(id!=null)
            {
                repositoriop.EliminarPropietario(id);
                this.ObtenerPropietarios();

            }
        }
        
        public void OnPostAdd(Propietario propietario)
        {
            Console.WriteLine("Propietario: "+propietario.nombre);
            repositoriop.AgregarPropietario(propietario);
            this.ObtenerPropietarios();

        }

         public void OnPostBuscar(string textBuscar)
        {
            Console.WriteLine("on pos buscar: "+textBuscar);
            this.textBuscar=textBuscar;
            
            this.listaPropietar=(IEnumerable<Propietario>)repositoriop.BuscarPropietarioNombre(textBuscar);
            //var mecanicos=repositorio.BuscarMecanicoNombre(textBuscar);

        }

        public void ObtenerPropietarios()
        {
             this.listaPropietar=(IEnumerable<Propietario>)repositoriop.ObtenerPropietarios();
             /*this.listaPropietar.Clear();
             foreach (var m in repositoriop.ObtenerPropietarios())
             {
                this.listaPropietar.Add(new Propietario(){
                PropietarioId=m.PropietarioId,
                nombre=m.nombre,
                telefono=m.telefono,
                fechaNacimiento=m.fechaNacimiento,
                contrasenia=m.contrasenia,
                ciudad=m.ciudad,
                correo=m.correo,
                });

             }*/
        }

        public void ObtenerPropietarios(string id)
        {
             this.listaPropietar=(IEnumerable<Propietario>)repositoriop.ObtenerPropietarios(id);
             /*this.listaPropietar.Clear();
             foreach (var m in repositoriop.ObtenerPropietarios())
             {
                this.listaPropietar.Add(new Propietario(){
                PropietarioId=m.PropietarioId,
                nombre=m.nombre,
                telefono=m.telefono,
                fechaNacimiento=m.fechaNacimiento,
                contrasenia=m.contrasenia,
                ciudad=m.ciudad,
                correo=m.correo,
                });

             }*/
        }



    }
    

    



}

Taller.App/Taller.App.Front/Pages/Propietarios/RegistroPropietario.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Taller.App.Front.Pages
{
    public class RegistroPropietarioModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Taller.App/Taller.App.Front/Pages/Propietarios/EditarPropietario.cshtml
@page
@model Taller.App.Front.Pages.EditarPropietarioModel
@{
}
<a class="btn btn-warning" asp-area="" asp-page="/Propietarios/GestionPropietario">Regresar</a>
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Formulario -Editar Propietario</h5>
        
      </div>
      <form class="px-12" method="POST">
      <div class="modal-body">
      
      <div class="row">
        <div class="mb-3 col-4">
        <label for="recipient-name" class="col-form-label">Id:</label>
        <input type="text" class="form-control" placeholder="Ingrese su Identificación" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.PropietarioId" name="PropietarioId" readonly>
        </div>
        <div class="mb-3 col-4">
        <label for="recipient-name" class="col-form-label">Nombre</label>
        <input type="text" class="form-control" placeholder="Ingrese su Nombre" aria-label="Username" aria-describedby="basic-addon1"asp-for="@Model.propietarioActual.nombre" name="nombre">
        </div>
        <div class="mb-3 col-4">
        <label for="recipient-name" class="col-form-label">Teléfono</label>
        <input type="text" class="form-control" placeholder="Ingrese Número de Teléfono" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.telefono" name="telefono">
        </div>
      </div>
      <div class="row">
       <div class="mb-3 col-4">
       <label for="recipient-name" class="col-form-label">F.Nacimiento</label>
       <input type="date" class="form-control" placeholder="" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.fechaNacimiento" name="fechaNacimiento">
      </div>
      <div class="mb-3 col-4">
       <label for="recipient-name" class="col-form-label">Ciudad Residencia</label>
       <select class="form-select" id="inputGroupSelect01" asp-for="@Model.propietarioActual.ciudad" name="ciudad">
        <option selected>Elegir...</option>
          <option value="Armenia">Armenia</option>
          <option value="Barranquilla">Barranquilla</option>
          <option value="Bogotá">Bogotá</option>
          <option value="Bucaramanga">Bucaramanga</option>
          <option value="Cali">Cali</option>
          <option value="Cartagena">Cartagena</option>
          <option value="Cúcuta">Cúcuta</option>
          <option value="Florencia">Florencia</option>
          <option value="Ibagué">Ibagué</option>
          <option value="Leticia">Leticia</option>
          <option value="Manizales">Manizales</option>
          <option value="Medellín">Medellín</option>
          <option value="Mitú">Mitú</option>
          <option value="Mocoa">Mocoa</option>
          <option value="Montería">Montería</option>
          <option value="Neiva">Neiva</option>
          <option value="Pasto">Pasto</option>
          <option value="Pereira">Pereira</option>
          <option value="Popayán">Popayán</option>
          <option value="Puerto Carreño">Puerto Carreño</option>
          <option value="Puerto Inírida">Puerto Inírida</option>
          <option value="Quibdó">Quibdó</option>
          <option value="Riohacha">Riohacha</option>
          <option value="San Andrés">San Andrés</option>
          <option value="San José del Guaviare">San José del Guaviare</option>
          <option value="Santa Marta">Santa Marta</option>
          <option value="Sincelejo">Sincelejo</option>
          <option value="Tunja">Tunja</option>
          <option value="Valledupar">Valledupar</option>
          <option value="Villavicencio">Villavicencio</option>
          <option value="Yopal">Yopal</option>
      </select>
      </div>
      <div class="mb-3 col-4">
    <label for="recipient-name" class="col-form-label">Correo</label>
    <input type="email" class="form-control" placeholder="Ingrese correo" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.correo" name="correo">
    <div id="emailHelp" class="form-text">Nunca Compartas tu correo.</div>
    </div>
    </div>
    <div class="row">
    <div class="mb-3 col-12">
    <label for="recipient-name" class="col-form-label">Contraseña</label>
    <input type="password" class="form-control" placeholder="" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.contrasenia" name="contrasenia">
    </div>
    </div>

      <div class="modal-footer">
        <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Actualizar</button>
        
      </div>
      </form>
    </div>
    
  </div>
</div>

Taller.App/Taller.App.Front/Pages/Propietarios/GestionPropietario.cshtml
@page
@model Taller.App.Front.Pages.GestionPropietarioModel
@{
}
<h4 id="idTitulo">Gestión Propietario</h4>
 <p>
 </p>
 <div class="text-center">
 <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="">Agregar Nuevo</button>
</div>
<div class="d-flex justify-content-end">
<nav class="navbar navbar-light bg-light">
 <form method="post" class="form-inline" style="display:flex;">
    <input name="textBuscar"class="form-control mr-sm-2" type="search" asp-for="@Model.textBuscar" placeholder="Búsqueda Propietario" aria-label="Ingrese Acá">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-page-handler="Buscar">Filtrar</button>
  </form>
</nav>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Numero de Teléfono</th>
      <th scope="col">Fecha de Nacimiento</th>
      <th scope="col">Ciudad</th>
      <th scope="col">Correo Electrónico</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
  @if(Model.listaPropietar != null){
 @foreach (var m in Model.listaPropietar){

    <tr>
      
      <td>@m.PropietarioId</td>
      <td>@m.nombre</td>
      <td>@m.telefono</td>
      <td>@m.fechaNacimiento</td>
      <td>@m.ciudad</td>
      <td>@m.correo</td>

      <td>@if(@Model.propietarioActual !=null && @Model.propietarioActual.PropietarioId!="")
      {
      <a class="bi bi-pencil-square class-icon-edit" asp-area="" asp-route-id="@m.PropietarioId" asp-page="/Propietarios/EditarPropietario"></a>
      <button type="submit" asp-route-id="@m.PropietarioId" class="bi bi-trash3-fill class-icon-delete" title="eliminar"></button>
      }else
      {
      <form class="px-12" method="POST">
      <a class="bi bi-pencil-square class-icon-edit" asp-area="" asp-route-id="@m.PropietarioId" asp-page="/Propietarios/EditarPropietario"></a>
      <button type="submit" asp-route-id="@m.PropietarioId" asp-page-handler="Del" class="bi bi-trash3-fill class-icon-delete" title="eliminar"></button>
      </form>

      }

      </td>
    </tr>}
  }
   </tbody>
</table>
 <p>
 <p>
<h5 id="idTitulo">Asociar Vehículo</h5>
 <p>
 </p>
 <div class="text-center">
 <a class="nav-link text-dark" asp-area="" asp-page="/Vehiculos/GestionVehiculo">Asociar Vehículo</a>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Formulario Inscripción - Nuevo Propietario</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form class="px-12" method="POST">
      <div class="modal-body">
      
      <div class="row">
        <div class="mb-3 col-6">
        <label for="recipient-name" class="col-form-label">Id:</label>
        <input type="text" class="form-control" placeholder="Ingrese su Identificación" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.PropietarioId" name="PropietarioId">
        </div>
        <div class="mb-3 col-6">
        <label for="recipient-name" class="col-form-label">Nombre</label>
        <input type="text" class="form-control" placeholder="Ingrese su Nombre" aria-label="Username" aria-describedby="basic-addon1"asp-for="@Model.propietarioActual.nombre" name="nombre">
        </div>
      </div>
      <div class="row">
      <div class="mb-3 col-6">
        <label for="recipient-name" class="col-form-label">Teléfono</label>
        <input type="text" class="form-control" placeholder="Ingrese Número de Teléfono" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.telefono" name="telefono">
        </div>
       <div class="mb-3 col-6">
       <label for="recipient-name" class="col-form-label">Fecha de Nacimiento</label>
       <input type="date" class="form-control" placeholder="" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.fechaNacimiento" name="fechaNacimiento">
      </div>
    </div>
    <div class="row">
      <div class="mb-3 col-6">
       <label for="recipient-name" class="col-form-label">Ciudad Residencia</label>
       <select class="form-select" id="inputGroupSelect01" asp-for="@Model.propietarioActual.ciudad" name="ciudad">
        <option selected>Elegir...</option>
          <option value="Armenia">Armenia</option>
          <option value="Barranquilla">Barranquilla</option>
          <option value="Bogotá">Bogotá</option>
          <option value="Bucaramanga">Bucaramanga</option>
          <option value="Cali">Cali</option>
          <option value="Cartagena">Cartagena</option>
          <option value="Cúcuta">Cúcuta</option>
          <option value="Florencia">Florencia</option>
          <option value="Ibagué">Ibagué</option>
          <option value="Leticia">Leticia</option>
          <option value="Manizales">Manizales</option>
          <option value="Medellín">Medellín</option>
          <option value="Mitú">Mitú</option>
          <option value="Mocoa">Mocoa</option>
          <option value="Montería">Montería</option>
          <option value="Neiva">Neiva</option>
          <option value="Pasto">Pasto</option>
          <option value="Pereira">Pereira</option>
          <option value="Popayán">Popayán</option>
          <option value="Puerto Carreño">Puerto Carreño</option>
          <option value="Puerto Inírida">Puerto Inírida</option>
          <option value="Quibdó">Quibdó</option>
          <option value="Riohacha">Riohacha</option>
          <option value="San Andrés">San Andrés</option>
          <option value="San José del Guaviare">San José del Guaviare</option>
          <option value="Santa Marta">Santa Marta</option>
          <option value="Sincelejo">Sincelejo</option>
          <option value="Tunja">Tunja</option>
          <option value="Valledupar">Valledupar</option>
          <option value="Villavicencio">Villavicencio</option>
          <option value="Yopal">Yopal</option>
      </select>
      </div>
      <div class="mb-3 col-6">
    <label for="recipient-name" class="col-form-label">Correo</label>
    <input type="email" class="form-control" placeholder="Ingrese correo" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.correo" name="correo">
    <div id="emailHelp" class="form-text">Nunca Compartas tu correo.</div>
    </div>
    </div>
    <div class="row">
    <div class="mb-3 col-12">
    <label for="recipient-name" class="col-form-label">Contraseña</label>
    <input type="password" class="form-control" placeholder="Ingrese nueva Contraseña" aria-label="Username" aria-describedby="basic-addon1" asp-for="@Model.propietarioActual.contrasenia" name="contrasenia">
    </div>
    </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary" asp-page-handler="Add">Registrar</button>
        
      </div>
      </form>
    </div>
    
  </div>
</div>
  

Taller.App/Taller.App.Front/Pages/Propietarios/RegistroPropietario.cshtml
@page
@model Taller.App.Front.Pages.RegistroPropietarioModel
@{
}
<h2 id="idTitulo">Registro Propietario Nuevo</h1>
<p>
</p>
<div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">Nombre</span>
  <input type="text" class="form-control" placeholder="Ingrese su nombre" aria-label="Username" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">Apellidos</span>
  <input type="text" class="form-control" placeholder="Ingrese los apellidos" aria-label="Username" aria-describedby="basic-addon1">
  </div>
   <div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">Número de Teléfono</span>
  <input type="text" class="form-control" placeholder="Ingrese Número de Teléfono" aria-label="Username" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">Fecha de Nacimiento</span>
  <input type="date" class="form-control" placeholder="" aria-label="Username" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
              <span class="input-group-text" id="basic-addon1">Correo Electrónico</span>
              <input id="idusuario" type="text" class="form-control" id="nombre" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text"> Nunca compartas tus datos de acceso.</div>
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
            </div>